### ISSUE TITLE
Global/continent view for (almost) all endpoints

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-server#11]
~The `country` field should also support the value `world` as well as the continent names and return values for the whole world or continent, respectively.~

~"world" and the continent names should however **not** be returned by the `/resource/country` endpoint.~

An additional `region` field should be introduced that accepts continent names. Both `country` and `region` should be optional and if none of them is provided, data for the whole world should be returned.

- [x] /resource/region
- [x] /resource/sample2
- [x] chen2021Fitness
- [x] sequencing intensity

**Comment by tehwalris** [comment]
I think its cleaner to make `country` an optional query param instead of having a special value.

**Comment by chaoran-chen** [comment]
Okay, we can do that as well. Then, a not provided `country` means the whole world.

**Comment by chaoran-chen** [comment]
The sequencing intensity endpoint will have to wait a little longer because we have to re-organize the database first.

**Comment by chaoran-chen** [comment]
Finished :)
